name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    env:
      GO_ENV: test

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Construct TEST_DATABASE_URL
      - name: Construct TEST_DATABASE_URL
        run: |
          echo "TEST_DATABASE_URL=postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV

      # Step 3: Wait for Database
      - name: Wait for Database
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database...";
            sleep 1;
          done
        shell: bash

      # Step 4: Run Tests
      - name: Run Tests
        run: go test ./unit_test/... -v
