name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: stadium_user
          POSTGRES_PASSWORD: secure_password
          POSTGRES_DB: stadium_builder_test

    env:
      # Hard coding these since the DB is a temporary service that gets torn down after the
      # pipeline is done.
      POSTGRES_USER: stadium_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: stadium_builder_test
      TEST_DATABASE_URL: postgres://stadium_user:secure_password@localhost:5432/stadium_builder_test
      GO_ENV: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for Database
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database...";
            sleep 1;
          done
        shell: bash

      - name: Debug TEST_DATABASE_URL
        run: echo "TEST_DATABASE_URL=$TEST_DATABASE_URL"

      - name: Run Tests
        run: go test ./unit_tests/... -v
