name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    env:
      TEST_DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      GO_ENV: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for Database
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database...";
            sleep 1;
          done
        shell: bash

      - name: Run Tests
        run: go test ./unit_tests/... -v
