name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping || exit 1"
          --health-interval=5s
          --health-retries=5
          --health-timeout=2s

    env:
      TEST_DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db
      REDIS_URL: redis://localhost:6379
      GO_ENV: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Wait for Database
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database...";
            sleep 1;
          done
        shell: bash

      - name: Wait for Redis
        run: |
          until redis-cli -h localhost ping; do
            echo "Waiting for Redis...";
            sleep 1;
          done
        shell: bash

      - name: Run Tests
        run: go test ./unit_tests/... -v
